# Generated by Django 2.1.4 on 2019-01-02 07:14

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Activity',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=100)),
                ('publication_date1', models.FloatField(max_length=100)),
                ('publication_date2', models.FloatField(max_length=100)),
                ('publication_date3', models.FloatField(max_length=100)),
                ('publication_date4', models.FloatField(max_length=100)),
                ('publication_date5', models.FloatField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='Analysis',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=50)),
                ('author', models.CharField(max_length=50)),
                ('publication_date1', models.DateField()),
            ],
        ),
        migrations.CreateModel(
            name='Company',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50)),
                ('code', models.IntegerField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='Finance',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=50)),
                ('publication_date1', models.URLField(max_length=100)),
                ('publication_date2', models.URLField(max_length=100)),
                ('publication_date3', models.URLField(max_length=100)),
                ('publication_date4', models.URLField(max_length=100)),
                ('publication_date5', models.URLField(max_length=100)),
                ('company', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='evComp.Company')),
            ],
        ),
        migrations.CreateModel(
            name='Growth',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=100)),
                ('publication_date1', models.FloatField(max_length=100)),
                ('publication_date2', models.FloatField(max_length=100)),
                ('publication_date3', models.FloatField(max_length=100)),
                ('publication_date4', models.FloatField(max_length=100)),
                ('publication_date5', models.FloatField(max_length=100)),
                ('company', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='evComp.Company')),
            ],
        ),
        migrations.CreateModel(
            name='Operation',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('owner', models.CharField(max_length=100)),
                ('publication_date1', models.DateField()),
                ('etc', models.CharField(max_length=100)),
                ('company', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='evComp.Company')),
            ],
        ),
        migrations.CreateModel(
            name='Profitability',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=100)),
                ('publication_date1', models.FloatField(max_length=100)),
                ('publication_date2', models.FloatField(max_length=100)),
                ('publication_date3', models.FloatField(max_length=100)),
                ('publication_date4', models.FloatField(max_length=100)),
                ('publication_date5', models.FloatField(max_length=100)),
                ('company', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='evComp.Company')),
            ],
        ),
        migrations.CreateModel(
            name='Stability',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=100)),
                ('publication_date1', models.FloatField(max_length=100)),
                ('publication_date2', models.FloatField(max_length=100)),
                ('publication_date3', models.FloatField(max_length=100)),
                ('publication_date4', models.FloatField(max_length=100)),
                ('publication_date5', models.FloatField(max_length=100)),
                ('company', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='evComp.Company')),
            ],
        ),
        migrations.AddField(
            model_name='analysis',
            name='company',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='evComp.Company'),
        ),
        migrations.AddField(
            model_name='activity',
            name='company',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='evComp.Company'),
        ),
    ]
